Xiao_bai/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
import xadmin

from novel import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),  # 首页url视图
    url(r'^admin/', include(xadmin.site.urls)), #后台url视图
    url(r'^users/', include('users.urls', namespace="users")), #用户中心相关的url视图
    url(r'^captcha/', include('captcha.urls')), #生成验证码
    url(r'^novel/', include('novel.urls', namespace = "novel")), #小说相关的url视图
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #图片的url连接

apps/novel/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^index/$', IndexView.as_view(), name="index" ), #首页url视图
    url(r'^tege/$', TageView.as_view(), name="noveltage"), #用于小说分类的url视图
    url(r'^book/(?P<book_id>\d+)/$', BookDetailsView.as_view(), name="book"), #用于小说的详情视图处理
    url(r'^text/(?P<text_id>\d+)/$', TextView.as_view(), name="text"), #用于小说内容的视图处理
    url(r'addfave/$', BookDetailsView.as_view(), name="addfave"),  # 用于把小说加入收藏处理
    url(r'PingView/$', PingView.as_view(), name="pingview"), #小说详情的评论加载 ---> 这个功能还没有完成
    url(r'search/$', SearchView.as_view(), name="search"), #小说的全局搜索url
]

apps/users/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^dl/$', IndexDlView.as_view(), name="dl"), #登陆的url视图处理
    url(r'^zc/$', IndexZcView.as_view(), name="zc"), #注册的url
    url(r'^out/$', LogoutView.as_view(), name="logout"), #用户退出
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(), name="active"), #用户账号激活
    url(r'^userhome/$', UserView.as_view(), name="userhome"), #用户的个人中心主页
    url(r'^usersite/$', UserSite.as_view(), name="usersiteup"), #用户中心的个人信息设置和POST请求请改昵称等信息
    url(r'^upimage/$', UploadImageView.as_view(), name="upimage"), #用户修改头像
    url(r'^uppassword/$', UpLoadPwdView.as_view(), name="uppassword"), #用户修改密码
    url(r'^upemail/$', UpEmailView.as_view(), name="upemail"), #给用户发送修改邮箱的验证码
    url(r'^upemails/$', UpEmailsView.as_view(), name="upemails"), #验证码邮箱和验证码是否匹配
    url(r'^message/$', UserMessage.as_view(), name="message"), #在用户中心显示当前用户的消息
    url(r'^userfave/$', UserFave.as_view(), name="userfave"), #用于处理用户的收藏url
    url(r'^userreader/$', ReadTextView.as_view(), name="userread"), #用于处理用户的浏览记录
    url(r'rest/$', ReadTextView.as_view(), name="rest"),  # 用于清除用户的小说的浏览记录
    url(r'^comment/$', CommentView.as_view(), name="comment"), #用于小说的评论
    url(r'^nouser/(?P<nouser_id>\d+)/$', UserNoLogView.as_view(), name="nouser"),  # 用于用户点击别的用户对象的时候跳转到别的用户中心响应视图
    url(r'^writing/$',WritingHomeView.as_view(), name="writinghome"), #用于作者的写作中心的主页视图


]

apps/users/forms.py
from django import forms
from .models import *

from captcha.fields import CaptchaField #验证码

#用户登陆验证
class DlForm(forms.Form):
    username = forms.CharField(required=True, error_messages={"required":"账号不能为空"})
    password = forms.CharField(required=True, min_length=5,error_messages={"required": "密码不能为空",})
   # captcha = CaptchaField(error_messages={"invalid":"验证码错误", "required":"验证码不能为空"}) #生成验证码

#用户的注册验证
class ZcForm(forms.Form):
    username = forms.CharField(required=True, error_messages={"required":"账号不能为空"})
    password = forms.CharField(required=True, max_length=32, min_length=8, error_messages={"required": "密码不能为空",})
    phone_number = forms.IntegerField(required=True, error_messages={"required": "手机号不能为空",})
    email = forms.EmailField(required=True, error_messages={"required":"邮箱不能为空"})


#用来修改用户中心的头像
class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProFile
        fields = ['image']


#密码修改
class MoforPwdForm(forms.Form):
    password1 = forms.CharField(required=True, error_messages={"required": "密码不能为空"})
    password2 = forms.CharField(required=True, error_messages={"required": "密码不能为空"})


#用来修改用户中心的信息
class UploadinfoForm(forms.ModelForm):
    class Meta:
        model = UserProFile
        fields = ['nick_name','birday','gender','address','mobile']


#用来验证用户的评论内容
class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModels
        fields = ['user_id','book_id','commtitle','comment']

apps/users/views.py
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.hashers import make_password #在用户注册的时候加密用户的密码

from .forms import DlForm, ZcForm, UploadImageForm, MoforPwdForm, UploadinfoForm, CommentForm
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger #用来加载分页器的异常
from util.mixin_utils import *
from .models import UserProFile, EmailVerifyRecord, Messages, Collection, ReadNovel
from util.email_send import *
from util.mixin_utils import LoginRequiredMIxin
from novel.models import NovelChaPter, NovelModel #用于收藏，通过章节表找到小说

# Create your views here.



'''用户的登陆响应'''
class IndexDlView(View):
    '''响应登陆页面'''
    def get(self, request):
        return render(request, 'login.html', locals())



    '''用于表单的登陆跳转'''
    def post(self, request):
        login_form = DlForm(request.POST)
        if login_form.is_valid():
            username = request.POST.get("username", "")
            password = request.POST.get("password", "")
            user = authenticate(username=username, password=password)
            if user is not None: #判断用户名密码是否正确
                if user.is_jh: #判断用户是否激活
                    login(request, user)
                    return HttpResponseRedirect("/")
                    #return render(request, "user.html", locals())
                else:
                    return HttpResponse('{"messages":"jh", "jh":"用户名未激活"}', content_type='application/json')
            else:
                return HttpResponse('{"messages":"cw", "cw":"用户名密码错误"}', content_type='application/json')
        else:
            return render(request, "login.html", locals())




'''用户注销登录功能'''
class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")




'''用户的注册功能响应'''
class IndexZcView(View):
    def get(self, request):
        return render(request, "register.html", locals())

    def post(self, request):
        register_form = ZcForm(request.POST)
        if register_form.is_valid():
            #获取所有的注册的post数据
            usernames = request.POST.get("username", "")
            password = request.POST.get("password", "")
            password2 = request.POST.get("confirm_password", "")
            phone_number = request.POST.get("phone_number", "")
            email = request.POST.get("email", "")
            #来判断用户名，邮箱，手机号是否注册过, 以及用户名密码是否正确
            if UserProFile.objects.filter(username=usernames):
                return HttpResponse('{"messages":"cw", "cw":"用户名存在"}', content_type='application/json')
            if UserProFile.objects.filter(mobile=phone_number):
                return HttpResponse('{"messages":"cw", "cw":"手机号已经存在"}', content_type='application/json')
            if UserProFile.objects.filter(email=email):
                return HttpResponse('{"messages":"cw", "cw":"邮箱已经存在"}', content_type='application/json')
            if password == password2:
                new_user = UserProFile()
                new_user.nick_name = usernames
                new_user.password = make_password(password)
                new_user.mobile = phone_number
                new_user.email = email
                new_user.is_jh = False
                new_user.username = usernames
                new_user.save()
                #注册成功后给用户发送一个激活邮件
                send_register_email(email, "register", new_user.nick_name)
                #注册成功后给用户发送一个系统消息
                messages = Messages()
                messages.user_name = new_user.id
                messages.mess_title = "账号注册成功"
                messages.mess_text = "亲爱的%s,欢迎注册小白读书网会员，在这里和大家一起读书交流吧！" % new_user.nick_name
                messages.save()
                return render(request, "login.html", locals())
            else:
                return HttpResponse('{"messages":"cw", "cw":"您输入的密码不一致"}', content_type='application/json')
        return render(request, "register.html", locals())



'''用户激活响应'''
class ActiveUserView(View):
    def get(self, request, active_code):
        emails_code = EmailVerifyRecord.objects.filter(code=active_code)
        if emails_code:
            for email_code in emails_code:
                if email_code.is_sx:
                    #激活用户
                    user = UserProFile.objects.get(email=email_code.email)
                    user.is_jh = True
                    user.save()
                    #激活成功后给用户发送一个系统消息
                    message = Messages()
                    message.user_name = user.id
                    message.mess_title = "账号激活成功"
                    message.mess_text = "亲爱的%s,您的会员账号已经成功激活，接下来就尽情的乐吧！"%user.nick_name
                    message.save()
                    #把验证码设为失效
                    email_code.is_sx = False
                    email_code.save()
                    return render(request, "active.html")
                else:
                    return HttpResponse("链接不小心丢失了，还望阁下不要伤心...")
        else:
            return HttpResponse("链接不小心丢失了，还望阁下不要伤心...")



'''跳转用户中心的url'''
class UserView(LoginRequiredMIxin, View):
    def get(self, request):
        msg = "home"
        #通过用户的ID查找到对应的用户对象
        #为了省时间就直接复制了，很多地方都是可以封装的
        no_user = UserProFile.objects.get(id=request.user.id)
        #通过用户找到用户的作品，和作品的更新时间
        no_user_novel = NovelModel.objects.filter(novel_user=request.user.id).order_by("-novel_time")
        #为用户中心的用户作品添加作品分页的功能
        page = request.GET.get('page', 1)
        try:
            page = request.GET.get('page', 1)
            p = Paginator(no_user_novel, 3, request=request)
            num = p.page(page)
        except EmptyPage:
            page = 1
            num = p.page(page)
        except PageNotAnInteger:
            page = 1
            num = p.page(page)
        except:
            page = 1
            num = p.page(page)
        return render(request, "user.html", locals())



'''用户中心的设置视图'''
class UserSite(LoginRequiredMIxin, View):
    def get(self, request):
        msg = "site"
        return render(request, "updatePage.html", locals())
    '''修改用户中心的昵称等信息'''
    def post(self, request):
        user_info_form = UploadinfoForm(request.POST, instance=request.user)
        # print(user_info_form)
        if user_info_form.is_valid():
            user_info_form.save()
            return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            return HttpResponse(json.dumps(user_info_form.errors), content_type='application/json')



'''用户修改头像'''
class UploadImageView(LoginRequiredMIxin, View):
    def post(self, request):
        image_form = UploadImageForm(request.POST, request.FILES, instance=request.user)
        if image_form.is_valid():
            image_form.save()
            return HttpResponse('{"status":"success", "msg":"修改成功"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"修改失败"}', content_type='application/json')


'''用户个人中心修改密码'''
class UpLoadPwdView(LoginRequiredMIxin,View):
    def post(self, request):
        mo_Pwd = MoforPwdForm(request.POST)
        if mo_Pwd.is_valid():
            pwd1 = request.POST.get("password1","")
            pwd2 = request.POST.get("password2","")
            if pwd1 != pwd2:
                return HttpResponse('{"status":"fail", "msg":"密码不相等"}', content_type='application/json')
            user = request.user
            user.password = make_password(pwd1)
            user.save()
            return HttpResponse('{"status":"success", "msg":"修改成功"}', content_type='application/json')
        else:
            return HttpResponse(json.dumps(modify_form.errors ), content_type='application/json')



'''用户修改个人邮箱'''
class UpEmailView(LoginRequiredMIxin, View):
    def get(self, request):
        email = request.GET.get("email", "")
        if email:
            if UserProFile.objects.filter(email=email):
                return HttpResponse('{"email":"邮箱不可用"}', content_type='application/json')
            send_register_email(email, "upload_email")
        return HttpResponse('{"status":"success"}', content_type='application/json')



'''验证更换邮箱的验证码和邮箱是否匹配'''
class UpEmailsView(LoginRequiredMIxin, View):
    def post(self, request):
        email = request.POST.get("email", "")
        code = request.POST.get("code", "")
        if code and email:
            email_code = EmailVerifyRecord.objects.get(email=email, code=code, send_type="upload_email")
            if email_code and email_code.is_sx:
                user = request.user
                user.email = email
                user.save()
                email_code.is_sx = False
                email_code.save()
                email_upload(request.user.email, "OK")
                return HttpResponse('{"status":"success"}', content_type='application/json')
            else:
                return HttpResponse('{"email":"验证码失效"}', content_type='application/json')
        else:
            return HttpResponse('{"email":"验证码不能为空"}', content_type='application/json')



'''在个人中心显示我的消息'''
class UserMessage(LoginRequiredMIxin, View):
    def get(self, request):
        msg = "site"
        user_message = Messages.objects.filter(user_name=request.user.id).order_by("-mess_time")
        # 对消息进行分页
        try:
            page = request.GET.get('page', 1)
            p = Paginator(user_message, 4, request=request)
            message = p.page(page)
        except EmptyPage:
            page = 1
            message = p.page(page)
        except PageNotAnInteger:
            page = 1
            message = p.page(page)
        except:
            page = 1
            message = p.page(page)
        return render(request, "message.html", locals())



'''用户小说的收藏记录'''
class UserFave(LoginRequiredMIxin, View):
    #加载用户中心的收藏的响应
    def get(self, request):

templates/active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>小白读书账号激活</title>
</head>
<body>
<a href="{% url 'users:dl' %}">现在去激活</a>
</body>
</html>

templates/bast.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="Cache-Control" content="no-transform " />
<meta name="applicable-device" content="pc,mobile">
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
<meta name="msapplication-tap-highlight" content="no"/>
<meta name="format-detection" content="telphone=no, email=no"/>
<link rel="shortcut icon" href="">
<link href="{% static 'css/bootscript.css'%}" rel="stylesheet"/>
<link href="{% static 'css/jquery-confirm.css' %}" rel="stylesheet"/>
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"/>
<link href="{% static 'css/index.css' %}" rel="stylesheet"/>
<link href="{% static 'css/tipnav.css' %}" rel="stylesheet"/>
<link href="{% static 'css/catalog.css' %}?v=20160908" rel="stylesheet"/>
{% block cssjs %} {% endblock %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js_cs %} {% endblock %}
{% block title %}<title>{{ request.user.nick_name }}的个人中心</title>{% endblock %}
</head>
<body>

<header class="huabenheader hidden-lg hidden-md">
	<div class="HuabenNavTop">
		<div class="TopNav">
			<ul class="pull-right">
				<li><a href="{% url 'novel:search' %}" class="huaben-img-btn search">[搜索]</a></li>
				<li><a href="#" id="huabenMore" class="huaben-img-btn more">[菜单]</a></li>
			</ul>
			<div class="hlogo">
				<a href="/">
					<img alt="话本小说" src="{% static '/images/logo.png' %}"/>
				</a>
			</div>
		</div>

		<div class="TopButtons">
			<ul>
				<li><a href="{% url 'index' %}"><i class="hicon-home"></i><span>首页</span></a></li>
				<li><a href="{% url 'novel:noveltage' %}"><i class="hicon-catalog"></i><span>分类</span></a></li>
			</ul>
			<ul>
				<li><a href="{% url 'users:userfave' %}"><i class="hicon-shelf"></i><span>收藏</span></a></li>
				<li><a href=""><i class="hicon-write"></i><span>写作</span></a></li>
				<li><a href="{% url 'users:userhome' %}"><i class="hicon-my"></i><span>我的</span></a></li>
			</ul>
		</div>
	</div>
	<div class="TopButtonsBG"></div>
	<div class="TopButtonsSpace"></div>
</header>


<header class="huabenheader hidden-xs hidden-sm">
	<div class="container HuabenNavTop">
		<div class="pull-left hlogo">
      <a href="{% url 'index' %}">
					<img alt="小白读书" src="{% static '/images/logo.png' %}"/>
			</a>
		</div>
		<ul class="pull-right list-inline">
			<li>
                <a href="{% url 'users:userfave' %}" class="bookshelf">书架</a>
            </li>
            {% if request.user.is_authenticated %}
            <li id="nav_usercenter_bar" style="">
				<a href="{% url 'users:userhome' %}" class="userpic">
				<img src="../../../Banner/{{ request.user.image }}" id="user_head_bar" alt="陈冠佑">
				<span>{{ request.user.nick_name }}</span>
				<iframe id="tmp_downloadhelper_iframe" style="display: none;"></iframe>
                </a>
			</li>
            {% else %}
            <li id="nav_login_bar" style="">
                <a href="{% url 'users:dl' %}" class="avatar">登录</a>
                <iframe id="tmp_downloadhelper_iframe" style="display: none;">
                </iframe>
            </li>
            {% endif %}
			<li id="nav_usercenter_bar" style="display: none;">
				<a href="{% url 'users:userhome' %}" class="userpic">
				<img src="" id="user_head_bar"/>
				</a>
			</li>
		</ul>
		<div class="text-center">
			<form action="{% url 'novel:search' %}" method="get" id="newSearchForm">
			<div class="searchForm" id="susearch">
				<input type="text" id="newSearchInput" name="keyword" placeholder="搜索">
				<button type="submit" id="susearch"></button>
			</div>
                {% csrf_token %}
			</form>
		</div>
	</div>
</header>
<div class="HuabenNav hidden-xs hidden-sm">
	<div class="container">
{#		<div class="pull-right">#}
{#			<ul class="list-inline HuabenNavButton">#}
{#				<li><a href="#" class="huaben-btn huaben-btn-yellow"><i class="icon-money"></i>写作福利</a></li>#}
{#				<li><a href="{% url 'users:writinghome' %}" class="huaben-btn huaben-btn-red"><i class="icon-coffee"></i>写作后台</a></li>#}
{#			</ul>#}
{#		</div>#}
		<div>
			<ul class="list-inline navTab" lang="navTab">
				<li><a href="{% url 'index' %}"><span>首页</span></a></li>
				<li><a href="{% url 'novel:noveltage' %}"><span>分类</span></a></li>
			</ul>
		</div>
	</div>
</div>
{% block container %}
<div class="container">
	<ul class="nav nav-tabs subnavigator" id="user_nav_bar">
		<li {% if msg == 'home' %}class="active"{% endif %}><a href="{% url 'users:userhome' %}">主页</a></li>
		<li {% if msg == 'site' %}class="active"{% endif %}><a href="{% url 'users:usersiteup' %}">设置</a></li>
		<li class="pull-right"><a href="{% url 'users:logout' %}">退出</a></li>
	</ul>
</div>
{% block center %}
	 <div class="container">
		<div class="text-center">
			<h3>&nbsp;</h3>
			<img src="../../../../Banner/{{ request.user.image }}" style="width: 80px;height: 80px;" class="img-circle" id="user_center_picurl">
				<em class="vip_icon_ol"></em>
			<h3 class="text-center text-warning">你好！{{ request.user.nick_name }}</h3>
			<hr/>
		</div>
    </div>
            <div class="mybookslist">
            {% for no_user_novel in num.object_list %}
                <div class="searchresult">
                    <div>
                        <img class="img-rounded" src="../../../../Banner/{{ no_user.image }}">
                        <p class="text-muted">
                            <span class="text-muted">{{ no_user.nick_name }}</span>
                            <small>{{ no_user_novel.novel_time|date:"Y-m-d H:i" }}</small>
                        </p>
                        <h1>
                            <a href="{% url 'novel:book' no_user_novel.id %}" target="_blank" class="text-info">{{ no_user_novel.novel_name }}</a>
                        </h1>
                    </div>
                    <div class="clearfix searchresult-info">
                        <p>
                            <a href="{% url 'novel:book' no_user_novel.id %}" target="_blank">{{ no_user_novel.novel_text }}</a>
                        </p>
                        <ul class="list-inline text-muted">
                            <li>{{ no_user_novel.novel_next }}人看过</li>
                            <li>&nbsp;</li>
                        {% if no_user_novel.novel_tage.all %}
                            <li>标签：</li>
                            <li>
                                <i class="text-muted">{% for tag in no_user_novel.novel_tage.all %}{{ tag }}  {% endfor %}</i>
                            </li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    <!--用户小说作品的分页--->
                <div class="text-center">
                <div class="pagination">
                <div class="btn-group">
                {% if num.has_previous %}
                    <a class="btn btn-default" a href="?{{ num.previous_page_number.querystring }}">«</a>
                    {% endif %}
                {% for page in num.pages %}
                     {% if page %}
                    {% ifequal page num.number %}
                    <a class="btn btn-default active"  href="?{{ page.querystring }}">{{ page }}</a>
                    {% else %}
                    <a class="btn btn-default" href="?{{ page.querystring }}">{{ page }}</a>
                    {% endifequal %}
                    {% endif %}
                {% endfor %}
                {% if num.has_next %}
                    <a class="btn btn-default" href="?{{ num.next_page_number.querystring }}">»</a>
                {% endif %}
                </div>
            </div>
		</div>
{% endblock %}
{% endblock %}
﻿<!--通用底部开始-->
	<div class="container navFooter">
		<div class="text-center footer">
			<ul>
				<li><a href="" target="_blank">关于我们</a></li>
				<li><a href="" target="_blank">加入我们</a></li>
				<li><a href="" target="_blank">联系我们</a></li>
				<li><a href="" target="_blank">帮助中心</a></li>
			</ul>
			<div class="text-center" style="margin-top:-10px;">
				<ul class="foot2 visible-xs-block">
					<li><a href="" class="text-dark">下载客户端</a></li>
					<li><a href="" class="text-dark">关注微博</a></li>
					<li class="text-dark">QQ群：********</li>
				</ul>
				<ul class="foot2 hidden-xs" id="QRlist"></ul>
{#				<p style="margin-top:3px;">&copy;2017 ***.com 京ICP备******号 *******科技有限公司 <a href="" target="_blank" class="text-dark">版权保护声明</a></p>#}
{#				<p style="margin-top:3px;">北京市朝阳区**********室 010-********</p>#}
				<div id="QRcode" style="display:none;position:absolute;" class="text-center">
					<img border="0"/>
					<p class="text-center"></p>
				</div>
			</div>
		</div>
	</div>
<!--通用底部结束-->
{% block db_js %}
{% endblock %}
</div>
</body>
</html>

templates/login.html
{% extends 'user_base.html' %}
{% block base_title %}
    <title>欢迎登陆|小白读书</title>
{% endblock %}
{% block base_count %}
    <div class="login-container">
        <h1>小白读书|会员登录</h1>
        <div class="connect">
            <p>登陆，马上读好书</p>
        </div>
        <form action="{% url 'users:dl' %}" method="post" id="loginForm">
            <div>
                <input type="text" name="username" class="username" placeholder="用户名" autocomplete="off"/>
            </div>
            <div>
                <input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false" onpaste="return false" />
            </div>
            <button id="submit" type="submit">登 陆</button>
            {% csrf_token %}
        </form>
        <a href="{% url 'users:zc' %}">
            <button type="button" class="register-tis">还有没有账号？</button>
        </a>
        <br>
        <a href="{% url 'users:zc' %}">
            <button type="button" class="register-tis">忘记密码了？</button>
        </a>
    </div>
{% endblock %}

templates/register.html
{% extends 'user_base.html' %}

templates/search.html
{% extends 'bast.html' %}
{% block title %}
    <title>{% if search_novel.object_list %}关于{{ search_key }}的全部结果{% else %}没有找到任何内容{% endif %}</title>
{% endblock %}
{% block container %}
    {% load staticfiles %}
        <div class="container">
           {% if msg == "no" %}
               <div class="notfound">
                    <img src="{% static 'images/notfound.png@200w.png' %}"><h2>没有搜索到相关内容</h2>
                   <iframe id="tmp_downloadhelper_iframe" style="display: none;"></iframe></div>
               </div>
            {% else %}
                {% for key in search_novel.object_list %}
                    <div class="searchresult">
                        <div>
                            <a href="{% url 'users:nouser' key.novel_user.id %}" target="_blank"><img class="img-rounded" src="../../../../Banner/{{ key.novel_user.image }}"></a>
                            <p class="text-muted"><span><a href="{% url 'users:nouser' key.novel_user.id %}" class="text-muted" target="_blank">{{ key.novel_user.nick_name }}</a></span> <small>{{ key.novel_time|date:"Y-m-d" }}</small></p>
                            <h2><a href="{% url 'novel:book' key.id %}" target="_blank">{{ key.novel_name }}</a></h2>
                        </div>
                        <div class="clearfix searchresult-info">
                            <p><a href="{% url 'novel:book' key.id %}" target="_blank">{{ key.novel_text }}</a></p>
                            <ul class="list-inline text-muted">
                                <li>{{ key.novel_next }}人看过</li>

                            </ul>
                        <iframe id="tmp_downloadhelper_iframe" style="display: none;"></iframe></div>
                    </div>
                {% endfor %}
                            <div class="text-center">
                        <div class="pagination">
                        <div class="btn-group">
                        {% if search_novel.has_previous %}
                            <a class="btn btn-default" a href="?{{ search_novel.previous_page_number.querystring }}">«</a>
                            {% endif %}
                        {% for page in search_novel.pages %}
                             {% if page %}
                            {% ifequal page search_novel.number %}
                            <a class="btn btn-default active"  href="?{{ page.querystring }}">{{ page }}</a>
                            {% else %}
                            <a class="btn btn-default"  href="?{{ page.querystring }}">{{ page }}</a>
                            {% endifequal %}
                            {% endif %}
                        {% endfor %}
                        {% if search_novel.has_next %}
                            <a class="btn btn-default" href="?{{ search_novel.next_page_number.querystring }}">»</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
                <nav class="text-center searchpagenav">
                    <ul class="pagination">
                    </ul>
                </nav>
        {% endif %}
{% endblock %}